# Generated by Django 4.1 on 2022-09-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('estatistica', models.CharField(max_length=100, verbose_name='Estatísticas')),
                ('infromacao', models.TextField(max_length=250, verbose_name='Informações')),
            ],
            options={
                'verbose_name': 'Sobre',
            },
        ),
    ]
